import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import FooterComponent from "./_components/footerComponent/footerComponent";
import HeaderComponent from "./_components/headerComponent/headerComponent";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Judson Ciribelli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black antialiased`}>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
